name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with Ruff
      run: |
        pip install ruff
        ruff --output-format=github .
    - name: Download latest example sentences
      run: python download.py
    - name: Convert sentence data to JSON
      run: python parse.py
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jpn-eng-examples.zip
        path: dist
