name: release

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"

env:
  MAJOR_VERSION: 0
  MINOR_VERSION: 0
    
jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  release:
    runs-on: ubuntu-latest
    needs: build
    name: Publish new release
    steps:
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: Changelog
        env:
          REPO: ${{github.repository}}
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          RELEASE_TAG: v$MAJOR_VERSION.$MINOR_VERSION.${{github.run_number}}_${{github.ref}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: $RELEASE_TAG
          release_name: Release $RELEASE_TAG
          body: |
            ${{ steps.Changelog.outputs.changelog }}
          draft: false
          prerelease: false