name: Release

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"

env:
  MAJOR_VERSION: 0
  MINOR_VERSION: 0
    
jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  release:
    runs-on: ubuntu-latest
    needs: build
    name: Publish new release
    steps:
      - uses: actions/checkout@v4
      - name: Get build artifacts from build step
        uses: actions/download-artifact@v3
        with:
          name: jpn-eng-examples.zip
          path: dist
      - name: Publish release
        env:
          RELEASE_TAG: v${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.${{github.run_number}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release create ${{env.RELEASE_TAG}} --generate-notes './dist/jpn-eng-examples.json'