name: Release

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 0 * * 0"

env:
  MAJOR_VERSION: 0
  MINOR_VERSION: 0
  JSON_FILENAME: jpn-eng-examples.zip
    
jobs:
  build:
    uses: ./.github/workflows/build.yml
  
  release:
    runs-on: ubuntu-latest
    needs: build
    name: Publish new release
    steps:
      - uses: actions/checkout@v4
      - name: Get build artifacts from build step
        uses: actions/download-artifact@v3
        with:
          name: ${{env.JSON_FILENAME}}
          path: dist
      - name: Zip artifact for deployment
        run: zip ${{env.JSON_FILENAME}} ./dist/* -r
      - name: Publish release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          RELEASE_TAG: v${{env.MAJOR_VERSION}}.${{env.MINOR_VERSION}}.${{github.run_number}}
        run: gh release create ${{env.RELEASE_TAG}} --generate-notes '${{env.JSON_FILENAME}}'